server:
  port: 8081

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka