server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/config


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/